server:
  port: 8088
spring:
  datasource:
    url: jdbc:h2:mem:school;DB_CLOSE_DELAY=-1;
    driverClassName: org.h2.Driver
    username: admin
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  flyway:
    url: jdbc:h2:mem:school
    user: admin
    password: